server:
  port: 30003

#spring:
#  profiles:
#    active: standalone
spring:
  data:
    mongodb:
      authentication-database: admin
      database: admin
      username: root
      password: YOUR_PASSWORD
      host: my-mongodb-standalone.mongodb.svc.cluster.local
      port: 27017
